# Baseball Project

In [1]:
import pandas as pd

In [2]:
batting_25_df = pd.read_csv('./Batting_2025.csv')
batting_25_df.head(10)

,Rk,Player,Age,Team,Lg,WAR,G,PA,AB,R,...,Rbat+,TB,GIDP,HBP,SH,SF,IBB,Pos,Awards,Player-additional
0,1,Francisco Lindor#,31,NYM,NL,5.8,160,732,644,117,...,128.0,300,9,16,0,7,2,*6/DH,AS,lindofr01
1,2,Rafael Devers*,28,2TM,2LG,4.0,163,729,607,99,...,139.0,291,16,6,0,4,10,*D3/5H,NaN,deverra01
2,2,Rafael Devers*,28,BOS,AL,2.3,73,334,272,47,...,153.0,137,7,4,0,2,7,D,NaN,deverra01
3,2,Rafael Devers*,28,SFG,NL,1.8,90,395,335,52,...,127.0,154,9,2,0,2,3,D3/5H,NaN,deverra01
4,3,Shohei Ohtani*,30,LAD,NL,6.6,158,727,611,146,...,175.0,380,9,3,0,2,20,*D1,AS,ohtansh01
5,4,Matt Olson*,31,ATL,NL,6.1,162,724,624,98,...,136.0,302,14,4,0,5,2,*3,AS,olsonma02
6,5,Kyle Schwarber*,32,PHI,NL,4.7,162,724,604,111,...,149.0,340,4,11,0,1,6,*D/7,AS,schwaky01
7,6,Geraldo Perdomo#,25,ARI,NL,7.0,161,720,597,98,...,139.0,276,11,10,8,11,1,*6/H,NaN,perdoge01
8,7,Juan Soto*,26,NYM,NL,6.2,160,715,577,120,...,163.0,303,17,3,1,6,13,*9/D,NaN,sotoju01
9,8,Julio Rodríguez,24,SEA,AL,6.8,160,710,652,106,...,133.0,309,15,12,0,2,5,*8/DH,AS,rodriju01

In [4]:
batting_24_df = pd.read_csv('./Batting_2024.csv')
batting_24_df.head(10)

,Rk,Player,Age,Team,Lg,WAR,G,PA,AB,R,...,Rbat+,TB,GIDP,HBP,SH,SF,IBB,Pos,Awards,Player-additional
0,1,Jarren Duran*,27,BOS,AL,8.7,160,735,671,111,...,134.0,330,6,6,1,3,1,*87,ASMVP-8,duranja01
1,2,Shohei Ohtani*,29,LAD,NL,9.2,159,731,636,134,...,190.0,411,7,6,0,5,10,*D,ASMVP-1SS,ohtansh01
2,3,Gunnar Henderson*,23,BAL,AL,9.1,159,719,630,118,...,157.0,333,2,7,0,4,1,*6/D,ASMVP-4,hendegu01
3,4,Marcus Semien,33,TEX,AL,4.1,159,718,650,101,...,100.0,254,9,3,0,1,2,*4,AS,semiema01
4,5,Juan Soto*,25,NYY,AL,7.9,157,713,576,128,...,179.0,328,10,4,0,4,2,*9/7DH,ASMVP-3SS,sotoju01
5,6,Bobby Witt Jr.,24,KCR,AL,9.4,161,709,636,125,...,171.0,374,4,8,0,8,9,*6/D,ASMVP-2GGSS,wittbo02
6,7,Aaron Judge,32,NYY,AL,10.8,158,704,559,122,...,223.0,392,22,9,0,2,20,*8D/97,ASMVP-1SS,judgeaa01
7,8,Vladimir Guerrero Jr.,25,TOR,AL,6.2,159,697,616,98,...,165.0,335,16,5,0,4,12,*3D5/H,ASMVP-6SS,guerrvl02
8,9,Elly De La Cruz#,22,CIN,NL,5.2,160,696,618,105,...,122.0,291,12,6,2,1,2,*6/H,ASMVP-8,delacel01
9,10,Pete Alonso,29,NYM,NL,2.6,162,695,608,91,...,122.0,279,14,13,0,4,4,*3/DH,AS,alonspe01